### PR TITLE
Remove cgi

### LINKED ISSUE #14: cgi deprecated in python 3.13
### What maintenance does this project need?

In my testbank, I now get the following warning:
```
  /opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/multiurl/http.py:10: DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
    import cgi
```

Since I did not see an issue about it yet, it seemed wise to report it.

### Organisation

Deltares

### PR DESCRIPTION
**Pull request by ocefpaf**
Fixes #14

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](https://bol-claassistant.ecmwf.int:443/ecmwf/multiurl?pullRequest=15) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf/multiurl?pullRequest=15) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf/multiurl?pullRequest=15) it.</sub>

**Comment by ocefpaf** [comment]
> is there any chance you can update the PR with QA fix applied?

Sure. Done in the last commit.

**Comment by EddyCMWF** [comment]
Hi again, sory for the delay on following up on this. I had to update the GH actions on the main branch. Could you please merge from main so that the python3.7 test is removed

**Comment by ocefpaf** [comment]
> Hi again, sory for the delay on following up on this. I had to update the GH actions on the main branch. Could you please merge from main so that the python3.7 test is removed

Done!

**Comment by EddyCMWF** [comment]
Mnay thanks for your contributions @ocefpaf !

**Pull request merged**
